package com.alaishat.mohammad.clean.docdoc.presentation.theme

import androidx.compose.ui.graphics.Color

//val primaryLight = Color(0xFF455E91)
val primaryLight = Color(0xFF247CFF)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E2FF)
val onPrimaryContainerLight = Color(0xFF001A43)
val secondaryLight = Color(0xFF575E71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDBE2F9)
val onSecondaryContainerLight = Color(0xFF141B2C)
val tertiaryLight = Color(0xFF715573)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFCD7FB)
val onTertiaryContainerLight = Color(0xFF2A132D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCFCFC)
val onBackgroundLight = Color(0xFF1A1B20)
val surfaceLight = Color(0xFFFAF9FF)
val onSurfaceLight = Color(0xFF1A1B20)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFF757780)
val outlineVariantLight = Color(0xFFC5C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFAEC6FF)

val Seed = Color(0xFF247CFF)
val Gray = Color(0xFF757575)
val UnfocusedTextFieldStrokeColor = Color(0xFFEDEDED)
val FocusedTextFieldStrokeColor = Color(0xFF247CFF)
val TextFieldBackgroundColor = Color(0xFFFDFDFF)

val OnSuccessContainerColor = Color(0xFF014100)
val SuccessContainerColor = Color(0xFFD6FFE1)
val TextFieldErrorStrokeColor = Color(0xFFFF4C5E)
//val Gray = Color(0xFF757575)
val DocDocSurface = Color(0xFFF4F8FF)
val DocDocUnselectedChipContainer = Color(0xFFF2F4F7)
val DocDocUnselectedChipLabel = Color(0xFFC2C2C2)
